/**
 * Formats a Date object to ICS/Zapier compliant string (YYYYMMDDTHHmmSSZ)
 * We treat the local time as the intended time for simplicity in this MVP, 
 * or convert to UTC if needed. Here we use UTC to be safe.
 */
function formatDateToICS(dateStr) {
    const date = new Date(dateStr);
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

/**
 * Generates a Google Calendar URL for the given todo item
 */
export function generateGoogleCalendarUrl(todo) {
    const title = encodeURIComponent(todo.title);
    const details = encodeURIComponent(`Note: ${todo.note || ''}\nType: ${todo.type}\nGenerated by Pixel Todo`);

    const start = new Date(todo.deadline);
    const end = new Date(start.getTime() + 60 * 60 * 1000); // Default duration 1 hour

    const startStr = formatDateToICS(start);
    const endStr = formatDateToICS(end);

    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&dates=${startStr}/${endStr}`;
}

/**
 * Generates and triggers a download of an .ics file for the given todo item
 */
export function downloadICS(todo) {
    const start = new Date(todo.deadline);
    const end = new Date(start.getTime() + 60 * 60 * 1000); // Default 1 hr
    const now = new Date();

    const icsContent = [
        'BEGIN:VCALENDAR',
        'VERSION:2.0',
        'PRODID:-//PixelTodo//EN',
        'BEGIN:VEVENT',
        `UID:${todo.id}@pixeltodo.app`,
        `DTSTAMP:${formatDateToICS(now)}`,
        `DTSTART:${formatDateToICS(start)}`,
        `DTEND:${formatDateToICS(end)}`,
        `SUMMARY:${todo.title}`,
        `DESCRIPTION:Type: ${todo.type}\\nNote: ${todo.note || ''}`,
        'END:VEVENT',
        'END:VCALENDAR'
    ].join('\r\n');

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `${todo.title.replace(/\s+/g, '_')}.ics`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}
